name: Deploy to GCP STAGING VM

on:
  push:
    branch:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_gcp
          chmod 600 ~/.ssh/id_rsa_gcp
          ssh-keyscan ${{ secrets.SSH_HOST_STAGING }} >> ~/.ssh/known_hosts

      
      - name: SSH into VM and deploy
        run: |
          ssh -i ~/.ssh/id_rsa_gcp -t ${{ secrets.SSH_USER_STAGING }}@${{ secrets.SSH_HOST_STAGING }}

    
